apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: application
build:
  artifacts:
  - image: application
    context: application
    docker:
      dockerfile: Dockerfile
      cacheFrom:
        - application
        - application:latest
    sync:
      infer:
      - '**/*.js'
      - '**/*.json'
manifests:
  kustomize:
    paths:
    - overlays/dev
deploy:
  kubectl: {}
profiles:
- name: prod
  manifests:
    kustomize:
      paths:
      - overlays/prod
- name: staging
  manifests:
    kustomize:
      paths:
      - overlays/staging